version: "3.7"

services:
  sem_trade:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        COMMIT: "${COMMIT}"
    container_name: sem_trade
    restart: always
    environment:
      1C_LOGIN: ${CRM_LOGIN}
      1C_PASSWORD: ${CRM_PASSWORD}
      MONGO_USER: ${MONGO_USER}
      MONGO_PASS: ${MONGO_PASS}
      MONGO_DB: ${MONGO_DB}
      MONGO_HOST: ${MONGO_HOST}
      SECRET_KEY: ${SECRET_KEY}
      INTERNAL_PORT: ${INTERNAL_PORT}
      COMMIT_HASH: ${COMMIT}
    ports:
      - "${INTERNAL_PORT}:80"

  mongodb:
    image: docker.io/bitnami/mongodb
    ports:
      - "27017:27017"
    volumes:
      - 'mongodb_data:/bitnami/mongodb'
    environment:
      MONGODB_USERNAME: ${MONGO_USER}
      MONGODB_PASSWORD: ${MONGO_PASS}
      MONGODB_DATABASE: ${MONGO_DB}


volumes:
  mongodb_data:
    driver: local