version: '3'

services:
  sem_trade:
    image: docker.pkg.github.com/io112/sem-trade/sem-trade:${GITHUB_SHA}
    container_name: sem_trade
    restart: always
    environment:
      CRM_LOGIN: ${CRM_LOGIN}
      CRM_PASSWORD: ${CRM_PASSWORD}
      MONGO_USER: ${MONGO_USER}
      MONGO_PASS: ${MONGO_PASS}
      MONGO_DB: ${MONGO_DB}
      MONGO_HOST: ${MONGO_HOST}
      SECRET_KEY: ${SECRET_KEY}
      INTERNAL_PORT: ${INTERNAL_PORT}
      COMMIT_HASH: ${COMMIT}
      LISTEN_PORT: ${INTERNAL_PORT}
      ROOT_USERNAME: ${ROOT_USERNAME}
      ROOT_PASSWORD: ${ROOT_PASSWORD}
      MAIL_SERVER: ${MAIL_SERVER}
      MAIL_PORT: ${MAIL_PORT}
      MAIL_USERNAME: ${MAIL_USERNAME}
      MAIL_PASSWORD: ${MAIL_PASSWORD}
      CURRENT_HOST: ${CURRENT_HOST}
      INSTANCE: ${INSTANCE}
    ports:
      - "${INTERNAL_PORT}:${INTERNAL_PORT}"

  mongodb:
    image: docker.io/bitnami/mongodb
    ports:
      - "27017:27017"
    volumes:
      - 'mongodb_data:/bitnami/mongodb'
    environment:
      MONGODB_USERNAME: ${MONGO_USER}
      MONGODB_PASSWORD: ${MONGO_PASS}
      MONGODB_DATABASE: ${MONGO_DB}


volumes:
  mongodb_data:
    driver: local